### ISSUE TITLE
Python3 test fail

### ISSUE THREAD

**Issue by bartTC** [bartTC/django-memcache-status#15]
The tests fail for Python3 as the underlaying `python-memcached` library fails to read stats due to encoding (byte vs. string) errors. 

Need to investigate further and check if their tests handle this already. Some quick fixes with six, unicode literals and re/encoding didn't fixed it, without breaking other parts of the lib.

The related code is [here](https://github.com/linsomniac/python-memcached/blob/master/memcache.py#L334-L339).

Full traceback:

``````
======================================================================
ERROR: test_cache_stats_included (memcache_status.tests.tests.MemcacheStatusSanityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/martin/Workspace/django-memcache-status/memcache_status/tests/tests.py", line 17, in test_cache_stats_included
    response = self.client.get('/admin/')
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/test/client.py", line 503, in get
    **extra)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/test/client.py", line 304, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/test/client.py", line 380, in generic
    return self.request(**r)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/test/client.py", line 467, in request
    six.reraise(*exc_info)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/utils/six.py", line 686, in reraise
    raise value
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/test/utils.py", line 92, in instrumented_test_render
    return self.nodelist.render(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/martin/Workspace/django-memcache-status/memcache_status/templatetags/memcache_status_tags.py", line 33, in render
    this_backend_stats = cache_backend._cache.get_stats()
  File "/tmp/tox/django-memcache-status/py35-django-19/lib/python3.5/site-packages/memcache.py", line 338, in get_stats
    stats = line.split(' ', 2)
TypeError: a bytes-like object is required, not 'str'```
``````

**Comment by bartTC** [comment]
Pushed a `python3` branch which uses the `python3-memcache` library fork https://github.com/bartTC/django-memcache-status/tree/python3

**Comment by bartTC** [comment]
The `python3` branch uses a fixed version of `python-memcache`. This needs to be fixed upstream before it can be resolved here.

**Comment by bartTC** [comment]
This has been fixed upstream.
