### ISSUE TITLE
django-memcache-status is not compatible with django-debug-toolbar >= 1.4

### ISSUE THREAD

**Issue by emorozov** [bartTC/django-memcache-status#16]
Using django-memcache-status and django-debug-toolbar in a single project results in an exception when trying to open any page:

```
[27/Jul/2016 10:32:05] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/data/cache/buildout/eggs/Django-1.9.7-py2.7.egg/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
  File "/data/cache/buildout/eggs/Django-1.9.7-py2.7.egg/django/core/handlers/base.py", line 230, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/data/cache/buildout/eggs/Django-1.9.7-py2.7.egg/django/core/handlers/base.py", line 296, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/data/cache/buildout/eggs/Django-1.9.7-py2.7.egg/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/data/cache/buildout/eggs/Django-1.9.7-py2.7.egg/django/views/defaults.py", line 60, in server_error
    template = loader.get_template(template_name)
  File "/data/cache/buildout/eggs/Django-1.9.7-py2.7.egg/django/template/loader.py", line 26, in get_template
    engines = _engine_list(using)
  File "/data/cache/buildout/eggs/Django-1.9.7-py2.7.egg/django/template/loader.py", line 143, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/data/cache/buildout/eggs/Django-1.9.7-py2.7.egg/django/template/utils.py", line 110, in all
    return [self[alias] for alias in self]
  File "/data/cache/buildout/eggs/Django-1.9.7-py2.7.egg/django/template/utils.py", line 101, in __getitem__
    engine = engine_cls(params)
  File "/data/cache/buildout/eggs/Django-1.9.7-py2.7.egg/django/template/backends/django.py", line 31, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/data/cache/buildout/eggs/Django-1.9.7-py2.7.egg/django/template/backends/django.py", line 49, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/data/cache/buildout/eggs/Django-1.9.7-py2.7.egg/django/template/backends/django.py", line 142, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/data/cache/buildout/eggs/Django-1.9.7-py2.7.egg/django/template/backends/django.py", line 159, in get_package_libraries
    "trying to load '%s': %s" % (entry[1], e)
InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'memcache_status.templatetags.memcache_status_tags': cannot import name get_cache
```

I think this happens because memcache-status is trying to load some debug-toolbar internal cache aliases that were renamed in the last toolbar releases.

**Comment by bartTC** [comment]
I tested it with debug-toolbar 1.7 and its working fine. The error message looks like you didn't add 'memcache_status' to the installed apps setting. Could you test it again?
